version: '3'
services:
  proxy: 
    container_name: proxy
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
  nginx-blog:
    container_name: nginx-blog
    image: nginx
    expose:
      - 80
    volumes:
      - ./nginx/blog-nginx.conf:/etc/nginx/nginx.conf
    environment:
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: blog.logathrim.local

  nginx-profile:
    container_name: nginx-profile
    image: nginx
    expose:
      - 80
    volumes:
      - ./nginx/profile-nginx.conf:/etc/nginx/nginx.conf
    environment:
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: profile.logathrim.local

  web-blog:
    container_name: blog
    image: node:17-alpine
    volumes:
      - .:/usr/app
    expose:
      - 5000
    command:
      sh -c "cd /usr && mkdir -p app && cd app && npm install yarn && yarn && node server/blog-server.js"

  web-profile:
    container_name: profile
    image: node:17-alpine
    volumes:
      - .:/usr/app
    expose:
      - 5000
    command:
      sh -c "cd /usr && mkdir -p app && cd app && npm install yarn && yarn && node server/profile-server.js"

networks:
  default:
    external:
      name: sandbox_network